add location
ng-japan/ng-japan.github.io pull request #5
Opened 2017-03-24 00:53 UTC by yoshiko-pg

location追加しました
https://yoshiko-sandbox.github.io/ng-japan.github.io/

2017-03-24 06:26 UTC, lacolaco requested changes
slackで要望を伝えました

2017-03-25 14:59 UTC, lacolaco approved these changes
よさそう！

2017-03-25 15:01 UTC, laco0416 commented
もうマージ可能？

2017-03-25 15:14 UTC, yoshiko-pg commented
@laco0416 今Speakersやってたけど、先Locationだけでもいいならもうマージしてもいいよ！
タイミング任せます！

2017-03-25 15:37 UTC, laco0416 commented
やってるなら待ちます！

2017-03-25 15:49 UTC, yoshiko-pg commented
@laco0416 追加したよー　どうかな？
https://yoshiko-sandbox.github.io/ng-japan.github.io/
トーク詳細にいくわけじゃないのでhoverエフェクトはなしにしてる

2017-03-25 23:48 UTC, laco0416 commented
LGTM!

2017-03-25 23:49 UTC, laco0416 commented
`Microsoft Japan` に https://www.microsoft.com/ja-jp/mscorp/branch/sgt.aspx へのリンク貼ってもらうとよさそう

2017-03-26 00:12 UTC, lacolaco requested changes
後はリンクだけあればOK

2017-03-26 00:34 UTC, lacolaco approved these changes
LGTM!

2017-03-26 00:35 UTC, yoshiko-pg commented
@laco0416 背景ずれたの直すからちょっとまって〜〜

2017-03-26 01:14 UTC, yoshiko-pg commented
@laco0416 マージOKです！

2017-03-26 01:46 UTC, merged

2017-03-26 01:47 UTC, laco0416 commented
Thx!